nginx:
  build: nginx
  env_file: docker-env
  ports:
    - "80:80"
  volumes:
    - ~/www:/var/www/html
  links:
    - php
  tty: true

php:
  build: php
  env_file: docker-env
  ports:
    - "9000:9000"
  volumes:
    - ~/www:/var/www/html
  links:
    - mysql
    - elasticsearch
  tty: true

mysql:
  image: mariadb:latest
  env_file: docker-env
  ports:
    - "3306:3306"
  tty: true

elasticsearch:
  image: elasticsearch:1.7
  env_file: docker-env
  ports:
    - "9200:9200"
    - "9300:9300"
  tty: true
